OMNeT++ NEDXML: NEDElement Class Reference
NEDElement Class Reference abstract
Data classes
#include <nedelement.h>
Description
Base class for objects in a NED object tree, the XML-based in-memory representation for NED files. An instance of a NEDElement subclass represent an XML element. NEDElement provides a DOM-like, generic access to the tree; subclasses additionally provide a typed interface.
Public Member Functions
Constructor, destructor
NEDElement ()
NEDElement (NEDElement *parent)
virtual ~NEDElement ()
virtual NEDElement * dup () const =0
virtual NEDElement * dupTree () const
Common properties
virtual const char * getTagName () const =0
virtual int getTagCode () const =0
virtual long getId () const
virtual void setId (long id)
virtual const char * getSourceLocation () const
virtual void setSourceLocation (const char *loc)
virtual const NEDSourceRegion & getSourceRegion () const
virtual void setSourceRegion (const NEDSourceRegion &region)
Generic access to attributes (Methods have to be redefined in subclasses!)
virtual void applyDefaults ()
virtual int getNumAttributes () const =0
virtual const char * getAttributeName (int k) const =0
virtual int lookupAttribute (const char *attr) const
virtual const char * getAttribute (int k) const =0
virtual const char * getAttribute (const char *attr) const
virtual void setAttribute (int k, const char *value)=0
virtual void setAttribute (const char *attr, const char *value)
virtual const char * getAttributeDefault (int k) const =0
virtual const char * getAttributeDefault (const char *attr) const
Generic access to children and siblings
virtual NEDElement * getParent () const
virtual NEDElement * getFirstChild () const
virtual NEDElement * getLastChild () const
virtual NEDElement * getNextSibling () const
virtual NEDElement * getPrevSibling () const
virtual void appendChild (NEDElement *node)
virtual void insertChildBefore (NEDElement *where, NEDElement *newnode)
virtual NEDElement * removeChild (NEDElement *node)
virtual NEDElement * getFirstChildWithTag (int tagcode) const
virtual NEDElement * getNextSiblingWithTag (int tagcode) const
virtual int getNumChildren () const
virtual int getNumChildrenWithTag (int tagcode) const
Utility functions
NEDElement * getFirstChildWithAttribute (int tagcode, const char *attr, const char *attrvalue=nullptr)
NEDElement * getParentWithTag (int tagcode)
User data
virtual void setUserData (NEDElementUserData *data)
virtual NEDElementUserData * getUserData () const
Static Public Member Functions
Counters
static long getNumCreated ()
static long getNumExisting ()
Static Protected Member Functions
static bool stringToBool (const char *s)
static const char * boolToString (bool b)
static int stringToEnum (const char *s, const char *vals[], int nums[], int n)
static const char * enumToString (int b, const char *vals[], int nums[], int n)
static void validateEnum (int b, const char *vals[], int nums[], int n)
Constructor & Destructor Documentation
NEDElement ()
Constructor
NEDElement (NEDElement * parent)
Constructor. Takes parent element.
virtual ~NEDElement () virtual
Destructor. Destroys children too.
Member Function Documentation
static bool stringToBool (const char * s) static protected
static const char* boolToString (bool b) static protected
static int stringToEnum (const char * s, const char * vals[], int nums[], int n) static protected
static const char* enumToString (int b, const char * vals[], int nums[], int n) static protected
static void validateEnum (int b, const char * vals[], int nums[], int n) static protected
virtual NEDElement* dup () const pure virtual
Creates and returns a duplicate of the element. Child elements are not copied.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual NEDElement* dupTree () const virtual
Recursive version of dup(): duplicates the whole subtree.
virtual const char* getTagName () const pure virtual
Overridden in subclasses to return the name of the XML element the class represents.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual int getTagCode () const pure virtual
Overridden in subclasses to return the numeric code (NED_xxx) of the XML element the class represents.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual long getId () const virtual
Returns a unique id, originally set by the constructor.
virtual void setId (long id) virtual
The unique id assigned by the constructor can be overwritten here.
virtual const char* getSourceLocation () const virtual
Returns a string containing a file/line position showing where this element originally came from.
virtual void setSourceLocation (const char * loc) virtual
Sets location string (a string containing a file/line position showing where this element originally came from). Called by the (NED/XML) parser.
virtual const NEDSourceRegion& getSourceRegion () const virtual
Returns the source region, containing a line:col region in the source file that corresponds to this element.
virtual void setSourceRegion (const NEDSourceRegion & region) virtual
Sets source region, containing a line:col region in the source file that corresponds to this element. Called by the (NED/XML) parser.
virtual void applyDefaults () virtual
Sets every attribute to its default value (as returned by getAttributeDefault()). Attributes without a default value are not affected.
This method is called from the constructors of derived classes.
virtual int getNumAttributes () const pure virtual
Pure virtual method, it should be redefined in subclasses to return the number of attributes defined in the DTD.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual const char* getAttributeName (int k) const pure virtual
Pure virtual method, it should be redefined in subclasses to return the name of the kth attribute as defined in the DTD.
It should return nullptr if k is out of range (i.e. negative or greater than getNumAttributes()).
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual int lookupAttribute (const char * attr) const virtual
Returns the index of the given attribute. It returns -1 if the attribute is not found. Relies on getNumAttributes() and getAttributeName().
virtual const char* getAttribute (int k) const pure virtual
Pure virtual method, it should be redefined in subclasses to return the value of the kth attribute (i.e. the attribute with the name getAttributeName(k)).
It should return nullptr if k is out of range (i.e. negative or greater than getNumAttributes()).
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
Referenced by FilesElement::getAttribute(), NedFileElement::getAttribute(), CommentElement::getAttribute(), PackageElement::getAttribute(), ImportElement::getAttribute(), PropertyDeclElement::getAttribute(), ExtendsElement::getAttribute(), InterfaceNameElement::getAttribute(), SimpleModuleElement::getAttribute(), ModuleInterfaceElement::getAttribute(), CompoundModuleElement::getAttribute(), ChannelInterfaceElement::getAttribute(), ChannelElement::getAttribute(), ParametersElement::getAttribute(), ParamElement::getAttribute(), PropertyElement::getAttribute(), PropertyKeyElement::getAttribute(), GatesElement::getAttribute(), GateElement::getAttribute(), TypesElement::getAttribute(), SubmodulesElement::getAttribute(), SubmoduleElement::getAttribute(), ConnectionsElement::getAttribute(), ConnectionElement::getAttribute(), ConnectionGroupElement::getAttribute(), LoopElement::getAttribute(), ConditionElement::getAttribute(), ExpressionElement::getAttribute(), OperatorElement::getAttribute(), FunctionElement::getAttribute(), IdentElement::getAttribute(), LiteralElement::getAttribute(), MsgFileElement::getAttribute(), NamespaceElement::getAttribute(), CplusplusElement::getAttribute(), StructDeclElement::getAttribute(), ClassDeclElement::getAttribute(), MessageDeclElement::getAttribute(), PacketDeclElement::getAttribute(), EnumDeclElement::getAttribute(), EnumElement::getAttribute(), EnumFieldsElement::getAttribute(), EnumFieldElement::getAttribute(), MessageElement::getAttribute(), PacketElement::getAttribute(), ClassElement::getAttribute(), StructElement::getAttribute(), FieldElement::getAttribute(), and UnknownElement::getAttribute().
virtual const char* getAttribute (const char * attr) const virtual
Returns the value of the attribute with the given name. Relies on lookupAttribute() and getAttribute().
It returns nullptr if the given attribute is not found.
Reimplemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual void setAttribute (int k, const char * value) pure virtual
Pure virtual method, it should be redefined in subclasses to set the value of the kth attribute (i.e. the attribute with the name getAttributeName(k)).
If k is out of range (i.e. negative or greater than getNumAttributes()), the call should be ignored.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
Referenced by FilesElement::setAttribute(), NedFileElement::setAttribute(), CommentElement::setAttribute(), PackageElement::setAttribute(), ImportElement::setAttribute(), PropertyDeclElement::setAttribute(), ExtendsElement::setAttribute(), InterfaceNameElement::setAttribute(), SimpleModuleElement::setAttribute(), ModuleInterfaceElement::setAttribute(), CompoundModuleElement::setAttribute(), ChannelInterfaceElement::setAttribute(), ChannelElement::setAttribute(), ParametersElement::setAttribute(), ParamElement::setAttribute(), PropertyElement::setAttribute(), PropertyKeyElement::setAttribute(), GatesElement::setAttribute(), GateElement::setAttribute(), TypesElement::setAttribute(), SubmodulesElement::setAttribute(), SubmoduleElement::setAttribute(), ConnectionsElement::setAttribute(), ConnectionElement::setAttribute(), ConnectionGroupElement::setAttribute(), LoopElement::setAttribute(), ConditionElement::setAttribute(), ExpressionElement::setAttribute(), OperatorElement::setAttribute(), FunctionElement::setAttribute(), IdentElement::setAttribute(), LiteralElement::setAttribute(), MsgFileElement::setAttribute(), NamespaceElement::setAttribute(), CplusplusElement::setAttribute(), StructDeclElement::setAttribute(), ClassDeclElement::setAttribute(), MessageDeclElement::setAttribute(), PacketDeclElement::setAttribute(), EnumDeclElement::setAttribute(), EnumElement::setAttribute(), EnumFieldsElement::setAttribute(), EnumFieldElement::setAttribute(), MessageElement::setAttribute(), PacketElement::setAttribute(), ClassElement::setAttribute(), StructElement::setAttribute(), FieldElement::setAttribute(), and UnknownElement::setAttribute().
virtual void setAttribute (const char * attr, const char * value) virtual
Sets the value of the attribute with the given name. Relies on lookupAttribute() and setAttribute().
If the given attribute is not found, the call has no effect.
Reimplemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual const char* getAttributeDefault (int k) const pure virtual
Pure virtual method, it should be redefined in subclasses to return the default value of the kth attribute, as defined in the DTD.
It should return nullptr if k is out of range (i.e. negative or greater than getNumAttributes()), or if the attribute is #REQUIRED; and return "" if the attribute is #IMPLIED.
Implemented in UnknownElement, FieldElement, StructElement, ClassElement, PacketElement, MessageElement, EnumFieldElement, EnumFieldsElement, EnumElement, EnumDeclElement, PacketDeclElement, MessageDeclElement, ClassDeclElement, StructDeclElement, CplusplusElement, NamespaceElement, MsgFileElement, LiteralElement, IdentElement, FunctionElement, OperatorElement, ExpressionElement, ConditionElement, LoopElement, ConnectionGroupElement, ConnectionElement, ConnectionsElement, SubmoduleElement, SubmodulesElement, TypesElement, GateElement, GatesElement, PropertyKeyElement, PropertyElement, ParamElement, ParametersElement, ChannelElement, ChannelInterfaceElement, CompoundModuleElement, ModuleInterfaceElement, SimpleModuleElement, InterfaceNameElement, ExtendsElement, PropertyDeclElement, ImportElement, PackageElement, CommentElement, NedFileElement, and FilesElement.
virtual const char* getAttributeDefault (const char * attr) const virtual
Returns the default value of the given attribute, as defined in the DTD. Relies on lookupAttribute() and getAttributeDefault().
It returns nullptr if the given attribute is not found.
virtual NEDElement* getParent () const virtual
Returns the parent element, or nullptr if this element has no parent.
virtual NEDElement* getFirstChild () const virtual
Returns pointer to the first child element, or nullptr if this element has no children.
virtual NEDElement* getLastChild () const virtual
Returns pointer to the last child element, or nullptr if this element has no children.
virtual NEDElement* getNextSibling () const virtual
Returns pointer to the next sibling of this element (i.e. the next child in the parent element). Returns nullptr if there're no subsequent elements.
getFirstChild() and getNextSibling() can be used to loop through the child list:
for (NEDElement *child=node->getFirstChild(); child; child = child->getNextSibling())
{
   ...
}
virtual NEDElement* getPrevSibling () const virtual
Returns pointer to the previous sibling of this element (i.e. the previous child in the parent element). Returns nullptr if there're no elements before this one.
virtual void appendChild (NEDElement * node) virtual
Appends the given element at the end of the child element list.
The node pointer passed should not be nullptr.
virtual void insertChildBefore (NEDElement * where, NEDElement * newnode) virtual
Inserts the given element just before the specified child element in the child element list, or at the end of the child list if nullptr is specified as the insert position.
The where element must be a child of this element, or nullptr. The node pointer passed should not be nullptr.
virtual NEDElement* removeChild (NEDElement * node) virtual
Removes the given element from the child element list.
The pointer passed should be a child of this element.
virtual NEDElement* getFirstChildWithTag (int tagcode) const virtual
Returns pointer to the first child element with the given tag code, or nullptr if this element has no such children.
virtual NEDElement* getNextSiblingWithTag (int tagcode) const virtual
Returns pointer to the next sibling of this element with the given tag code. Return nullptr if there're no such subsequent elements.
getFirstChildWithTag() and getNextSiblingWithTag() are a convient way to loop through elements with a certain tag code in the child list:
for (NEDElement *child=node->getFirstChildWithTag(tagcode); child; child = child->getNextSiblingWithTag(tagcode))
{
    ...
}
virtual int getNumChildren () const virtual
Returns the number of child elements.
virtual int getNumChildrenWithTag (int tagcode) const virtual
Returns the number of child elements with the given tag code.
NEDElement* getFirstChildWithAttribute (int tagcode, const char * attr, const char * attrvalue = nullptr)
Returns first child element with the given tagcode and the given attribute (optionally) having the given value. Returns nullptr if not found.
NEDElement* getParentWithTag (int tagcode)
Climb up in the element tree until it finds an element with the given tagcode. Returns "this" if its tagcode already matches. Returns nullptr if not found.
static long getNumCreated () inline static
Returns NEDElements constructed so far (this number can only increase).
static long getNumExisting () inline static
Returns NEDElements currently existing (created minus deleted). Useful for detecting memory leaks.
virtual void setUserData (NEDElementUserData * data) virtual
Replaces user data object with the given one.
virtual NEDElementUserData* getUserData () const virtual
Return pointer to the user data object, or nullptr if setUserData() has not been called yet.
The documentation for this class was generated from the following file:
nedelement.h