//
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2003 Ahmet Sekercioglu
// Copyright (C) 2003-2004 Andras Varga
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//
// $Id: tictoc13.msg,v 1.1 2005/09/28 23:59:14 ahmet Exp $

message TicTocMsg13
{
    int source;
    int destination;
    int hopCount = 0;
}
