OMNeT++ Simulation Library: cCanvas Class Reference
cCanvas Class Reference
Canvas (2D Graphics)
#include <ccanvas.h>
Description
Provides a scene graph based 2D drawing API for modules.
Notes:
all figures are under a root figure (which we try not to expose too much)
Z-order is defined by child order (bottom-to-top) and preorder traversal
layer-like functionality is provided via figure tags: the Tkenv UI will allow figures to be shown or hidden according to tags they contain
cModule has one dedicated canvas, additional canvas objects can be created
initial module canvas contents comes from @figure properties inside the compound module NED file, see samples/canvas for examples!
extensibility: type=foo in a @figure property will cause the canvas to look for a registered FooFigure or cFooFigure class to instantiate
dup() makes deep copy (duplicates the figure tree too)
the submodules layer (see getSubmodulesLayer()) is currently an empty placeholder figure where Tkenv will draw modules and connections (by means outside cCanvas/cFigure) – it can be used for Z-order positioning of other figures relative to the submodules and connections
Public Member Functions
Constructors, destructor, assignment.
cCanvas (const char *name=nullptr)
cCanvas (const cCanvas &other)
virtual ~cCanvas ()
cCanvas & operator= (const cCanvas &other)
Redefined cObject member functions.
virtual cCanvas * dup () const override
virtual void forEachChild (cVisitor *v) override
virtual std::string info () const override
Canvas attributes.
virtual const cFigure::Color & getBackgroundColor () const
virtual void setBackgroundColor (const cFigure::Color &color)
Managing child figures.
virtual cFigure * getRootFigure () const
virtual void addFigure (cFigure *figure)
virtual void addFigure (cFigure *figure, int pos)
virtual void addFigureAbove (cFigure *figure, cFigure *referenceFigure)
virtual void addFigureBelow (cFigure *figure, cFigure *referenceFigure)
virtual cFigure * removeFigure (int pos)
virtual cFigure * removeFigure (cFigure *figure)
virtual int findFigure (const char *name) const
virtual int findFigure (cFigure *figure) const
virtual bool hasFigures () const
virtual int getNumFigures () const
virtual cFigure * getFigure (int pos) const
virtual cFigure * getFigure (const char *name) const
Accessing the figure tree.
virtual cFigure * getSubmodulesLayer () const
virtual cFigure * findFigureRecursively (const char *name) const
virtual cFigure * getFigureByPath (const char *path) const
Figure tags.
virtual std::string getAllTags () const
virtual std::vector< std::string > getAllTagsAsVector () const
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual std::string detailedInfo () const
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Member Function Documentation
virtual cCanvas* dup () const inline override virtual
Should be redefined in subclasses to create an exact copy of this object. The default implementation just throws an error, to indicate that the method was not redefined.
Reimplemented from cObject.
References cFigure::addFigure(), cFigure::addFigureAbove(), cFigure::addFigureBelow(), cFigure::containsFigures(), cFigure::findFigure(), cFigure::findFigureRecursively(), cFigure::getFigure(), cFigure::getFigureByPath(), cFigure::getNumFigures(), and cFigure::removeFigure().
virtual void forEachChild (cVisitor * v) override virtual
Enables traversing the object tree, performing some operation on each object. The operation is encapsulated in the particular subclass of cVisitor.
This method should be redefined in every subclass to call v->visit(obj) for every obj object contained.
Reimplemented from cObject.
virtual std::string info () const override virtual
Can be redefined to produce a one-line description of object. The string appears in the graphical user interface (Tkenv) e.g. when the object is displayed in a listbox. The returned string should possibly be at most 80-100 characters long, and must not contain newline.
See also
detailedInfo()
Reimplemented from cObject.
The documentation for this class was generated from the following file:
ccanvas.h