OMNeT++ Simulation Library: cWeightedStdDev Class Reference
cWeightedStdDev Class Reference
Statistical Result Collection
#include <cstddev.h>
Description
Statistics class to collect doubles and calculate weighted statistics from them.
One application is to calculate time average.
Public Member Functions
Constructors, destructor, assignment.
cWeightedStdDev (const cWeightedStdDev &r)
cWeightedStdDev (const char *name=nullptr)
virtual ~cWeightedStdDev ()
cWeightedStdDev & operator= (const cWeightedStdDev &res)
Redefined cObject member functions.
virtual cWeightedStdDev * dup () const override
virtual std::string info () const override
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
Redefined cStatistic functions.
virtual void collect (double value) override
virtual void collect (SimTime value) override
virtual bool isWeighted () const override
virtual void collect2 (double value, double weight) override
virtual void collect2 (SimTime value, double weight)
virtual void collect2 (double value, SimTime weight)
virtual void collect2 (SimTime value, SimTime weight)
virtual void merge (const cStatistic *other) override
virtual void clearResult () override
virtual double getMean () const override
virtual double getVariance () const override
virtual double getWeights () const override
virtual double getWeightedSum () const override
virtual double getSqrSumWeights () const override
virtual double getWeightedSqrSum () const override
virtual void saveToFile (FILE *) const override
virtual void loadFromFile (FILE *) override
Public Member Functions inherited from cStdDev
cStdDev (const cStdDev &r)
cStdDev (const char *name=nullptr)
virtual ~cStdDev ()
cStdDev & operator= (const cStdDev &res)
virtual std::string detailedInfo () const override
virtual long getCount () const override
virtual double getSum () const override
virtual double getSqrSum () const override
virtual double getMin () const override
virtual double getMax () const override
virtual double getStddev () const override
virtual double draw () const override
Public Member Functions inherited from cStatistic
cStatistic (const cStatistic &r)
cStatistic (const char *name=nullptr)
virtual ~cStatistic ()
cStatistic & operator= (const cStatistic &res)
virtual void setTransientDetectionObject (cTransientDetection *object)
virtual void setAccuracyDetectionObject (cAccuracyDetection *object)
virtual cTransientDetection * getTransientDetectionObject () const
virtual cAccuracyDetection * getAccuracyDetectionObject () const
_OPPDEPRECATED double random () const
virtual void record ()
virtual void recordWithUnit (const char *unit)
virtual void recordAs (const char *name, const char *unit=nullptr)
Public Member Functions inherited from cRandom
cRandom (cRNG *rng)
cRandom (const char *name=nullptr, cRNG *rng=nullptr)
virtual ~cRandom ()
virtual void setRNG (cRNG *rng)
cRNG * getRNG () const
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cWeightedStdDev (const cWeightedStdDev & r) inline
Constructors, destructor, duplication and assignment.
cWeightedStdDev (const char * name = nullptr) inline explicit
Constructors, destructor, duplication and assignment.
virtual ~cWeightedStdDev () inline virtual
Constructors, destructor, duplication and assignment.
Member Function Documentation
cWeightedStdDev& operator= (const cWeightedStdDev & res)
Assignment operator. The name member is not copied; see cNamedObject's operator=() for more details.
virtual cWeightedStdDev* dup () const inline override virtual
Creates and returns an exact copy of this object. See cObject for more details.
Reimplemented from cStdDev.
virtual std::string info () const override virtual
Produces a one-line description of the object's contents. See cObject for more details.
Reimplemented from cStdDev.
virtual void parsimPack (cCommBuffer * buffer) const override virtual
Serializes the object into an MPI send buffer. Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStdDev.
virtual void parsimUnpack (cCommBuffer * buffer) override virtual
Deserializes the object from an MPI receive buffer Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStdDev.
virtual void collect (double value) inline override virtual
Collects one value.
Reimplemented from cStdDev.
virtual void collect (SimTime value) inline override virtual
Convenience method, delegates to collect(double).
Reimplemented from cStdDev.
References cWeightedStdDev::collect(), and SimTime::dbl().
Referenced by cWeightedStdDev::collect().
virtual bool isWeighted () const inline override virtual
Returns true, because this class collects weighted statistics.
Reimplemented from cStdDev.
virtual void collect2 (double value, double weight) override virtual
Collects one value with a given weight. Negative weights will cause a runtime error.
Reimplemented from cStatistic.
virtual void collect2 (SimTime value, double weight) inline virtual
Convenience method, delegates to collect2(double, double).
References cWeightedStdDev::collect2(), and SimTime::dbl().
Referenced by cWeightedStdDev::collect2().
virtual void collect2 (double value, SimTime weight) inline virtual
Convenience method, delegates to collect2(double, double).
References cWeightedStdDev::collect2(), and SimTime::dbl().
Referenced by cWeightedStdDev::collect2().
virtual void collect2 (SimTime value, SimTime weight) inline virtual
Convenience method, delegates to collect2(double, double).
References cWeightedStdDev::collect2(), and SimTime::dbl().
Referenced by cWeightedStdDev::collect2().
virtual void merge (const cStatistic * other) override virtual
Updates this object with data coming from another statistics object – as if this object had collected observations fed into the other object as well.
Reimplemented from cStdDev.
virtual void clearResult () override virtual
Clears the results collected so far.
Reimplemented from cStdDev.
virtual double getMean () const override virtual
Returns the weighted mean of the observations collected, or NaN if no observations have been collected (or their weights were 0).
Reimplemented from cStdDev.
virtual double getVariance () const override virtual
Returns the variance of the observations collected, or NaN if less than two observations have been collected.
Reimplemented from cStdDev.
virtual double getWeights () const inline override virtual
Returns the sum of weights.
Reimplemented from cStdDev.
virtual double getWeightedSum () const inline override virtual
Returns the sum of weight*value products.
Reimplemented from cStdDev.
virtual double getSqrSumWeights () const inline override virtual
Returns the sum of squared weights.
Reimplemented from cStdDev.
virtual double getWeightedSqrSum () const inline override virtual
Returns the sum of weight*value*value products.
Reimplemented from cStdDev.
virtual void saveToFile (FILE *) const override virtual
Writes the contents of the object into a text file.
Reimplemented from cStdDev.
virtual void loadFromFile (FILE *) override virtual
Reads the object data from a file, in the format written out by saveToFile().
Reimplemented from cStdDev.
The documentation for this class was generated from the following file:
cstddev.h