OMNeT++ Simulation Library: cFigure Class Reference
cFigure Class Reference abstract
Canvas (2D Graphics)
#include <ccanvas.h>
Description
A lightweight graphical object for cCanvas.
This is the central class of OMNeT++'s 2D drawing API. Graphical elements are called figures, and are represented by subclasses of cFigure. To display a figure-based drawing, one needs to add figures to a canvas (cCanvas). Every module has its own canvas, accessible via cModule::getCanvas(), and one may also create additional ones.
Notes:
figures can be hierarchical (resulting in a figure tree)
coordinates are in canvas units, not in pixels (interactive zooming!)
coordinates are transformed with the figure's own transform plus the transforms of all ancestors
a figure subtree can be hidden by calling setVisible(false)
the order of child figures also denotes drawing order (of overlapping figures, the last one will appear on top)
dup() makes shallow copy (doesn't copy child figures); see dupTree() as well
figures are only data storage classes, rendering is done in the back-end (e.g. Tkenv) by separate renderer classes.
See also
cCanvas
Classes
struct Color
Represents an RGB color.
struct Font
Represents properties of a font.
class Pixmap
A rectangular RGBA pixel array.
struct Point
Represents a point as (x,y) coordinates.
struct Rectangle
Represents a rectangle as an (x,y,width,height) tuple.
struct RGBA
Represents an RGBA pixel, for Pixmap manipulation.
struct Transform
Homogeneous 2D transformation matrix (last row is not stored).
Public Member Functions
Constructors, destructor, assignment
cFigure (const char *name=nullptr)
cFigure (const cFigure &other)
virtual ~cFigure ()
cFigure & operator= (const cFigure &other)
Redefined cObject member functions.
virtual cFigure * dup () const override
virtual void forEachChild (cVisitor *v) override
virtual std::string info () const override
Common figure attributes.
int getId () const
virtual bool isVisible () const
virtual void setVisible (bool visible)
virtual const Transform & getTransform () const
virtual void setTransform (const Transform &transform)
virtual const char * getTags () const
virtual void setTags (const char *tags)
Accessing the parent figure and child figures.
virtual cFigure * getParentFigure () const
virtual cCanvas * getCanvas () const
virtual int getNumFigures () const
virtual cFigure * getFigure (int pos) const
virtual cFigure * getFigure (const char *name) const
virtual int findFigure (const char *name) const
virtual int findFigure (cFigure *figure) const
virtual bool containsFigures () const
virtual cFigure * findFigureRecursively (const char *name) const
virtual cFigure * getFigureByPath (const char *path) const
virtual cFigure * removeFromParent ()
Managing child figures.
virtual void addFigure (cFigure *figure)
virtual void addFigure (cFigure *figure, int pos)
virtual void addFigureAbove (cFigure *figure, cFigure *referenceFigure)
virtual void addFigureBelow (cFigure *figure, cFigure *referenceFigure)
virtual cFigure * removeFigure (cFigure *figure)
virtual cFigure * removeFigure (int pos)
Changing the Z-order of this figure.
virtual void raiseAbove (cFigure *figure)
virtual void lowerBelow (cFigure *figure)
virtual void raiseToTop ()
virtual void lowerToBottom ()
Operations on the transformation matrix.
virtual void translate (double dx, double dy)
virtual void scale (double s)
virtual void scale (double sx, double sy)
virtual void scale (double sx, double sy, double cx, double cy)
virtual void scale (double sx, double sy, const Point &c)
virtual void rotate (double phi)
virtual void rotate (double phi, double cx, double cy)
virtual void rotate (double phi, const Point &c)
virtual void skewx (double coeff)
virtual void skewy (double coeff)
virtual void skewx (double coeff, double cy)
virtual void skewy (double coeff, double cx)
Miscellaneous.
virtual cFigure * dupTree () const
virtual void moveLocal (double dx, double dy)=0
virtual void move (double dx, double dy)
virtual const char * getRendererClassName () const =0
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual std::string detailedInfo () const
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Static Public Attributes
Predefined colors.
static const Color BLACK
static const Color WHITE
static const Color GREY
static const Color RED
static const Color GREEN
static const Color BLUE
static const Color YELLOW
static const Color CYAN
static const Color MAGENTA
static const int NUM_GOOD_DARK_COLORS
static const int NUM_GOOD_LIGHT_COLORS
static const Color GOOD_DARK_COLORS [14]
static const Color GOOD_LIGHT_COLORS [10]
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cFigure (const char * name = nullptr) explicit
Constructor.
cFigure (const cFigure & other) inline
Copy constructor. Child figures and the figure ID are not copied.
virtual ~cFigure () virtual
Destructor
Member Function Documentation
cFigure& operator= (const cFigure & other)
Assignment operator. It copies all data members except the object name, figure ID and child figures. (See cNamedObject's operator=() for details.)
virtual cFigure* dup () const inline override virtual
Clones the figure, ignoring its child figures. (The copy will have no children.) To clone a figure together with its figure subtree, use dupTree().
Reimplemented from cObject.
Reimplemented in cPixmapFigure, cIconFigure, cImageFigure, cAbstractImageFigure, cLabelFigure, cTextFigure, cAbstractTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cAbstractShapeFigure, cPolylineFigure, cArcFigure, cLineFigure, cAbstractLineFigure, and cGroupFigure.
virtual void forEachChild (cVisitor * v) override virtual
Calls v->visit(this) on each child figure. See cObject for more details.
Reimplemented from cObject.
virtual std::string info () const override virtual
Returns a one-line string with the most characteristic data of the figure.
Reimplemented from cObject.
Reimplemented in cPixmapFigure, cImageFigure, cAbstractTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cAbstractShapeFigure, cPolylineFigure, cArcFigure, cLineFigure, cAbstractLineFigure, and cGroupFigure.
int getId () const inline
Returns the unique ID of this figure object. This ID is mostly intended for internal use.
virtual bool isVisible () const inline virtual
Returns the visibility flag of the figure.
virtual void setVisible (bool visible) inline virtual
Sets the visibility flag of the figure. Setting the visibility flag to false will cause the whole figure subtree to be omitted from rendering.
virtual const Transform& getTransform () const inline virtual
Returns the transform associated with this figure.
virtual void setTransform (const Transform & transform) inline virtual
Sets the transform associated with this figure. The transform will affect the rendering of this figure and its whole figure subtree. The transform may also be modified with the various translate(), scale(), rotate(), skewx()/skewy() methods.
virtual const char* getTags () const inline virtual
Returns the space-separated list of the tags associated with the figure. Tags may be used in the GUI displaying a canvas for implementing layers or other kind of filtering.
virtual void setTags (const char * tags) virtual
Sets the list of tags associated with the figure. This method accepts a space-separated list of tags. (Tags themselves may not contain spaces; underscores are recommended instead where needed.)
virtual cFigure* getParentFigure () const inline virtual
Returns the figure of this figure, or nullptr if it has none.
virtual cCanvas* getCanvas () const virtual
Returns the canvas object to which this figure was added, or nullptr if there is no such canvas. Note that the runtime cost of this method is proportional to the depth of this figure in the figure tree.
virtual int getNumFigures () const inline virtual
Returns the number of child figures.
Referenced by cCanvas::dup().
virtual cFigure* getFigure (int pos) const virtual
Returns the kth figure in the child list. The index must be in the range 0..getNumFigures()-1. An out-of-bounds index will cause a runtime error.
Referenced by cCanvas::dup().
virtual cFigure* getFigure (const char * name) const virtual
Return a child figure by name, or nullptr if there is no such child figure.
virtual int findFigure (const char * name) const virtual
Finds the first figure with the given name among the children of this figure, and returns its index. If there is no such figure, -1 is returned.
Referenced by cCanvas::dup().
virtual int findFigure (cFigure * figure) const virtual
Finds the given figure among the children of this figure, and returns its index. If it is not found, -1 is returned.
virtual bool containsFigures () const inline virtual
Returns true of this figure has child figures, and false otherwise.
Referenced by cCanvas::dup().
virtual cFigure* findFigureRecursively (const char * name) const virtual
Find the first figure with the given name in this figure's subtree, including the figure itself. Returns nullptr if no such figure is found.
Referenced by cCanvas::dup().
virtual cFigure* getFigureByPath (const char * path) const virtual
Finds a figure in the subtree, given by its absolute or relative path. The path is a string of figure names separated by dots; the special module name ^ (caret) stands for the parent figure. If the path starts with a dot or caret, it is understood as relative to this figure, otherwise it is taken to mean an absolute path (i.e. relative to the root figure, see getRootFigure()). Returns nullptr if the figure was not found.
Examples:
"." means this figure;
".icon" means the child figure name "icon";
".group.label" means the "label" child of the "group" child figure;
"^.icon" or ".^.icon" means the "icon" sibling of this figure;
"icon" means the "icon" child of the root figure
The above syntax is similar to the one used by cModule::getModuleByPath()
Referenced by cCanvas::dup().
virtual cFigure* removeFromParent () virtual
Remove this figure from the child list of its parent figure.
virtual void addFigure (cFigure * figure) virtual
Appends the given figure to the list of children.
Referenced by cCanvas::dup().
virtual void addFigure (cFigure * figure, int pos) virtual
Inserts the given figure to the list of children at the given position.
virtual void addFigureAbove (cFigure * figure, cFigure * referenceFigure) virtual
Inserts the given figure into the child list after the reference figure.
Referenced by cCanvas::dup().
virtual void addFigureBelow (cFigure * figure, cFigure * referenceFigure) virtual
Inserts the given figure into the child list before the reference figure.
Referenced by cCanvas::dup().
virtual cFigure* removeFigure (cFigure * figure) virtual
Remove the given figure from the child list. An error is raised if the figure is not a child of this figure.
Referenced by cCanvas::dup().
virtual cFigure* removeFigure (int pos) virtual
Remove the kth figure from the child list. An error is raised if pos is not in the range 0..getNumFigures()-1.
virtual void raiseAbove (cFigure * figure) virtual
If this figure precedes (i.e. is drawn below) the given figure in the parent figure's child list, move it directly after. An error is raised if the two figures do not share the same parent.
virtual void lowerBelow (cFigure * figure) virtual
If this figure follows (i.e. is drawn above) the given figure in the parent figure's child list, move it directly before. An error is raised if the two figures do not share the same parent.
virtual void raiseToTop () virtual
Move this figure to the end of the child list in its parent, so that it is drawn above all its siblings. It is an error if this figure has no parent.
virtual void lowerToBottom () virtual
Move this figure to the beginning of the child list in its parent, so that it is drawn below all its siblings. It is an error if this figure has no parent.
virtual cFigure* dupTree () const virtual
Duplicate the figure subtree.
virtual void moveLocal (double dx, double dy) pure virtual
Change the figure's position by the given x and y deltas. Child figures will not be affected.
Implemented in cAbstractImageFigure, cAbstractTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cPolylineFigure, cArcFigure, cLineFigure, and cGroupFigure.
virtual void move (double dx, double dy) virtual
Change the position of this figure and the figures in its subtree by the given x and y deltas. The implementation of this method calls moveLocal() on this figure, then move() recursively on child figures.
virtual const char* getRendererClassName () const pure virtual
Returns the name of the class responsible for rendering this figure. Renderer classes are specific to, and are usually implemented as part of, the graphical user interface library (Tkenv or Qtenv).
Implemented in cPixmapFigure, cIconFigure, cImageFigure, cLabelFigure, cTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cPolylineFigure, cArcFigure, cLineFigure, and cGroupFigure.
The documentation for this class was generated from the following file:
ccanvas.h