//
// Generated file, do not edit! Created by nedtool 4.6 from messages/ReplyMsg.msg.
//

#ifndef _REPLYMSG_M_H_
#define _REPLYMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Class generated from <tt>messages/ReplyMsg.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // Adds a variable to save the source address, the msg was sent from.
 * //
 * packet ReplyMsg extends GenericAppMsg
 * {
 *     int connID;
 *     string vmaddress;
 *     int serviceport;
 *     double depTime;
 * }
 * </pre>
 */
class ReplyMsg : public ::GenericAppMsg
{
  protected:
    int connID_var;
    opp_string vmaddress_var;
    int serviceport_var;
    double depTime_var;

  private:
    void copy(const ReplyMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReplyMsg&);

  public:
    ReplyMsg(const char *name=NULL, int kind=0);
    ReplyMsg(const ReplyMsg& other);
    virtual ~ReplyMsg();
    ReplyMsg& operator=(const ReplyMsg& other);
    virtual ReplyMsg *dup() const {return new ReplyMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getConnID() const;
    virtual void setConnID(int connID);
    virtual const char * getVmaddress() const;
    virtual void setVmaddress(const char * vmaddress);
    virtual int getServiceport() const;
    virtual void setServiceport(int serviceport);
    virtual double getDepTime() const;
    virtual void setDepTime(double depTime);
};

inline void doPacking(cCommBuffer *b, ReplyMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ReplyMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _REPLYMSG_M_H_

