//
// Generated file, do not edit! Created by nedtool 4.6 from messages/RequestMsg.msg.
//

#ifndef _REQUESTMSG_M_H_
#define _REQUESTMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Class generated from <tt>messages/RequestMsg.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // Adds a variable to save the source address, the msg was sent from.
 * //
 * packet RequestMsg extends GenericAppMsg
 * {
 *     int connID;
 *     //bool queued = false;
 *     int serviceport;
 *     double depTime;
 * }
 * </pre>
 */
class RequestMsg : public ::GenericAppMsg
{
  protected:
    int connID_var;
    int serviceport_var;
    double depTime_var;

  private:
    void copy(const RequestMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestMsg&);

  public:
    RequestMsg(const char *name=NULL, int kind=0);
    RequestMsg(const RequestMsg& other);
    virtual ~RequestMsg();
    RequestMsg& operator=(const RequestMsg& other);
    virtual RequestMsg *dup() const {return new RequestMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getConnID() const;
    virtual void setConnID(int connID);
    virtual int getServiceport() const;
    virtual void setServiceport(int serviceport);
    virtual double getDepTime() const;
    virtual void setDepTime(double depTime);
};

inline void doPacking(cCommBuffer *b, RequestMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RequestMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _REQUESTMSG_M_H_

