//
// Generated file, do not edit! Created by nedtool 4.6 from messages/StartHV.msg.
//

#ifndef _STARTHV_M_H_
#define _STARTHV_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Enum generated from <tt>messages/StartHV.msg:12</tt> by nedtool.
 * <pre>
 * enum SourceNames
 * {
 * 
 *     VM = 0;
 *     CONTROLLER = 1;
 * }
 * </pre>
 */
enum SourceNames {
    VM = 0,
    CONTROLLER = 1
};

/**
 * Class generated from <tt>messages/StartHV.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // Msg to initiate the start of a hypervisor/server.
 * //
 * packet StartHV extends GenericAppMsg
 * {
 *     string hvaddress;
 *     int source @enum(SourceNames);
 *     bool serverState;
 * }
 * </pre>
 */
class StartHV : public ::GenericAppMsg
{
  protected:
    opp_string hvaddress_var;
    int source_var;
    bool serverState_var;

  private:
    void copy(const StartHV& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StartHV&);

  public:
    StartHV(const char *name=NULL, int kind=0);
    StartHV(const StartHV& other);
    virtual ~StartHV();
    StartHV& operator=(const StartHV& other);
    virtual StartHV *dup() const {return new StartHV(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getHvaddress() const;
    virtual void setHvaddress(const char * hvaddress);
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual bool getServerState() const;
    virtual void setServerState(bool serverState);
};

inline void doPacking(cCommBuffer *b, StartHV& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, StartHV& obj) {obj.parsimUnpack(b);}


#endif // ifndef _STARTHV_M_H_

