//
// Generated file, do not edit! Created by nedtool 4.6 from messages/StartVM.msg.
//

#ifndef _STARTVM_M_H_
#define _STARTVM_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Class generated from <tt>messages/StartVM.msg:13</tt> by nedtool.
 * <pre>
 * //
 * // Msg. to initiate the start of a vm.
 * //
 * packet StartVM extends GenericAppMsg
 * {
 *     string vmaddress;
 *     int serviceport;
 *     int connIDtoCon;
 *     bool serverState;
 *     int activeVMSize;
 * }
 * </pre>
 */
class StartVM : public ::GenericAppMsg
{
  protected:
    opp_string vmaddress_var;
    int serviceport_var;
    int connIDtoCon_var;
    bool serverState_var;
    int activeVMSize_var;

  private:
    void copy(const StartVM& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StartVM&);

  public:
    StartVM(const char *name=NULL, int kind=0);
    StartVM(const StartVM& other);
    virtual ~StartVM();
    StartVM& operator=(const StartVM& other);
    virtual StartVM *dup() const {return new StartVM(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getVmaddress() const;
    virtual void setVmaddress(const char * vmaddress);
    virtual int getServiceport() const;
    virtual void setServiceport(int serviceport);
    virtual int getConnIDtoCon() const;
    virtual void setConnIDtoCon(int connIDtoCon);
    virtual bool getServerState() const;
    virtual void setServerState(bool serverState);
    virtual int getActiveVMSize() const;
    virtual void setActiveVMSize(int activeVMSize);
};

inline void doPacking(cCommBuffer *b, StartVM& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, StartVM& obj) {obj.parsimUnpack(b);}


#endif // ifndef _STARTVM_M_H_

