//
// Generated file, do not edit! Created by nedtool 4.6 from messages/TTimer.msg.
//

#ifndef _TTIMER_M_H_
#define _TTIMER_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Class generated from <tt>messages/TTimer.msg:13</tt> by nedtool.
 * <pre>
 * //
 * // Traffic Timer messages are used to trigger the next RequestMsg.
 * //
 * packet TTimer extends GenericAppMsg
 * {
 * }
 * </pre>
 */
class TTimer : public ::GenericAppMsg
{
  protected:

  private:
    void copy(const TTimer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TTimer&);

  public:
    TTimer(const char *name=NULL, int kind=0);
    TTimer(const TTimer& other);
    virtual ~TTimer();
    TTimer& operator=(const TTimer& other);
    virtual TTimer *dup() const {return new TTimer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, TTimer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TTimer& obj) {obj.parsimUnpack(b);}


#endif // ifndef _TTIMER_M_H_

