//
// Generated file, do not edit! Created by nedtool 4.6 from messages/StartClient.msg.
//

#ifndef _STARTCLIENT_M_H_
#define _STARTCLIENT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GenericAppMsg_m.h"
// }}

/**
 * Class generated from <tt>messages/StartClient.msg:13</tt> by nedtool.
 * <pre>
 * //
 * // Used to start a client up.
 * //
 * packet StartClient extends GenericAppMsg
 * {
 *     int delay;
 *     bool clientIsOn;
 *     string clientAddr;
 *     int serviceport;
 * }
 * </pre>
 */
class StartClient : public ::GenericAppMsg
{
  protected:
    int delay_var;
    bool clientIsOn_var;
    opp_string clientAddr_var;
    int serviceport_var;

  private:
    void copy(const StartClient& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StartClient&);

  public:
    StartClient(const char *name=NULL, int kind=0);
    StartClient(const StartClient& other);
    virtual ~StartClient();
    StartClient& operator=(const StartClient& other);
    virtual StartClient *dup() const {return new StartClient(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDelay() const;
    virtual void setDelay(int delay);
    virtual bool getClientIsOn() const;
    virtual void setClientIsOn(bool clientIsOn);
    virtual const char * getClientAddr() const;
    virtual void setClientAddr(const char * clientAddr);
    virtual int getServiceport() const;
    virtual void setServiceport(int serviceport);
};

inline void doPacking(cCommBuffer *b, StartClient& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, StartClient& obj) {obj.parsimUnpack(b);}


#endif // ifndef _STARTCLIENT_M_H_

