//
// Generated file, do not edit! Created by nedtool 4.6 from components/TPacket.msg.
//

#ifndef _TPACKET_M_H_
#define _TPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>components/TPacket.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet TPacket
 * {
 *     int srcAddress;
 *     int destAddress;
 *     int hops = 0;
 * }
 * </pre>
 */
class TPacket : public ::cPacket
{
  protected:
    int srcAddress_var;
    int destAddress_var;
    int hops_var;

  private:
    void copy(const TPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TPacket&);

  public:
    TPacket(const char *name=NULL, int kind=0);
    TPacket(const TPacket& other);
    virtual ~TPacket();
    TPacket& operator=(const TPacket& other);
    virtual TPacket *dup() const {return new TPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual int getHops() const;
    virtual void setHops(int hops);
};

inline void doPacking(cCommBuffer *b, TPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _TPACKET_M_H_

