//
// Generated file, do not edit! Created by nedtool 5.0 from components/TPacket.msg.
//

#ifndef __TPACKET_M_H
#define __TPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>components/TPacket.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet TPacket
 * {
 *     int srcAddress;
 *     int destAddress;
 *     int hops = 0;
 * }
 * </pre>
 */
class TPacket : public ::omnetpp::cPacket
{
  protected:
    int srcAddress;
    int destAddress;
    int hops;

  private:
    void copy(const TPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TPacket&);

  public:
    TPacket(const char *name=nullptr, int kind=0);
    TPacket(const TPacket& other);
    virtual ~TPacket();
    TPacket& operator=(const TPacket& other);
    virtual TPacket *dup() const {return new TPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual int getHops() const;
    virtual void setHops(int hops);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TPACKET_M_H

