//
// Generated file, do not edit! Created by nedtool 5.0 from src/CoreNode/OBS_BCPControlInfo.msg.
//

#ifndef __OBS_BCPCONTROLINFO_M_H
#define __OBS_BCPCONTROLINFO_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/CoreNode/OBS_BCPControlInfo.msg:23</tt> by nedtool.
 * <pre>
 * // Control info object included in OBS_BurstControlPacket when converted to electrical.
 * class OBS_BCPControlInfo
 * {
 *     int port = -1; // BCP input/output fiber.
 *     simtime_t BCPArrival = -1; // BCPini arrival time.
 * }
 * </pre>
 */
class OBS_BCPControlInfo : public ::omnetpp::cObject
{
  protected:
    int port;
    ::omnetpp::simtime_t BCPArrival;

  private:
    void copy(const OBS_BCPControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_BCPControlInfo&);

  public:
    OBS_BCPControlInfo();
    OBS_BCPControlInfo(const OBS_BCPControlInfo& other);
    virtual ~OBS_BCPControlInfo();
    OBS_BCPControlInfo& operator=(const OBS_BCPControlInfo& other);
    virtual OBS_BCPControlInfo *dup() const {return new OBS_BCPControlInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual ::omnetpp::simtime_t getBCPArrival() const;
    virtual void setBCPArrival(::omnetpp::simtime_t BCPArrival);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OBS_BCPControlInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OBS_BCPControlInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef __OBS_BCPCONTROLINFO_M_H

