OMNeT++ Simulation Library: cStdDev Class Reference
cStdDev Class Reference
Statistical Result Collection
#include <cstddev.h>
Description
Statistics class to collect min, max, mean, and standard deviation.
Public Member Functions
Constructors, destructor, assignment.
cStdDev (const cStdDev &r)
cStdDev (const char *name=nullptr)
virtual ~cStdDev ()
cStdDev & operator= (const cStdDev &res)
Redefined cObject member functions.
virtual cStdDev * dup () const override
virtual std::string info () const override
virtual std::string detailedInfo () const override
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
Redefined cStatistic functions.
virtual void collect (double value) override
virtual void collect (SimTime value) override
virtual void merge (const cStatistic *other) override
virtual bool isWeighted () const override
virtual long getCount () const override
virtual double getSum () const override
virtual double getSqrSum () const override
virtual double getMin () const override
virtual double getMax () const override
virtual double getMean () const override
virtual double getStddev () const override
virtual double getVariance () const override
virtual double getWeights () const override
virtual double getWeightedSum () const override
virtual double getSqrSumWeights () const override
virtual double getWeightedSqrSum () const override
virtual double draw () const override
virtual void clearResult () override
virtual void saveToFile (FILE *) const override
virtual void loadFromFile (FILE *) override
Public Member Functions inherited from cStatistic
cStatistic (const cStatistic &r)
cStatistic (const char *name=nullptr)
virtual ~cStatistic ()
cStatistic & operator= (const cStatistic &res)
virtual void collect2 (double value, double weight)
virtual void setTransientDetectionObject (cTransientDetection *object)
virtual void setAccuracyDetectionObject (cAccuracyDetection *object)
virtual cTransientDetection * getTransientDetectionObject () const
virtual cAccuracyDetection * getAccuracyDetectionObject () const
_OPPDEPRECATED double random () const
virtual void record ()
virtual void recordWithUnit (const char *unit)
virtual void recordAs (const char *name, const char *unit=nullptr)
Public Member Functions inherited from cRandom
cRandom (cRNG *rng)
cRandom (const char *name=nullptr, cRNG *rng=nullptr)
virtual ~cRandom ()
virtual void setRNG (cRNG *rng)
cRNG * getRNG () const
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cStdDev (const cStdDev & r) inline
Copy constructor.
cStdDev (const char * name = nullptr) explicit
Constructor.
virtual ~cStdDev () inline virtual
Destructor.
Member Function Documentation
cStdDev& operator= (const cStdDev & res)
Assignment operator. The name member is not copied; see cNamedObject's operator=() for more details.
virtual cStdDev* dup () const inline override virtual
Creates and returns an exact copy of this object. See cObject for more details.
Reimplemented from cObject.
Reimplemented in cDoubleHistogram, cLongHistogram, cWeightedStdDev, cKSplit, cVarHistogram, and cPSquare.
virtual std::string info () const override virtual
Produces a one-line description of the object's contents. See cObject for more details.
Reimplemented from cObject.
Reimplemented in cWeightedStdDev.
virtual std::string detailedInfo () const override virtual
Produces a multi-line description of the object. See cObject for more details.
Reimplemented from cObject.
Reimplemented in cKSplit, cDensityEstBase, and cPSquare.
virtual void parsimPack (cCommBuffer * buffer) const override virtual
Serializes the object into an MPI send buffer. Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStatistic.
Reimplemented in cWeightedStdDev, cHistogram, cKSplit, cDensityEstBase, cVarHistogram, cPSquare, and cHistogramBase.
virtual void parsimUnpack (cCommBuffer * buffer) override virtual
Deserializes the object from an MPI receive buffer Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStatistic.
Reimplemented in cWeightedStdDev, cHistogram, cKSplit, cDensityEstBase, cVarHistogram, cPSquare, and cHistogramBase.
virtual void collect (double value) override virtual
Collects one value.
Implements cStatistic.
Reimplemented in cLongHistogram, cWeightedStdDev, and cDensityEstBase.
virtual void collect (SimTime value) inline override virtual
Convenience method, delegates to collect(double).
Reimplemented from cStatistic.
Reimplemented in cLongHistogram, cWeightedStdDev, and cDensityEstBase.
References cStdDev::collect(), and SimTime::dbl().
Referenced by cStdDev::collect().
virtual void merge (const cStatistic * other) override virtual
Updates this object with data coming from another statistics object – as if this object had collected observations fed into the other object as well. Throws an error if the other object is weighted statistics (see isWeighted()).
Implements cStatistic.
Reimplemented in cWeightedStdDev, cKSplit, cPSquare, and cDensityEstBase.
virtual bool isWeighted () const inline override virtual
Returns false, because this class does not collect weighted statistics.
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual long getCount () const inline override virtual
Returns the number of observations collected.
Implements cStatistic.
virtual double getSum () const inline override virtual
Returns the sum of the values.
Implements cStatistic.
virtual double getSqrSum () const inline override virtual
Returns the squared sum of the collected values.
Implements cStatistic.
virtual double getMin () const override virtual
Returns the minimum of the collected values, or NaN if none have been collected yet.
Implements cStatistic.
virtual double getMax () const override virtual
Returns the maximum of the collected values, or NaN if none have been collected yet.
Implements cStatistic.
virtual double getMean () const override virtual
Returns the mean of the collected values, or NaN if none have been collected yet.
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double getStddev () const override virtual
Returns the standard deviation of the observations, or NaN if less than two observations have been collected.
Implements cStatistic.
virtual double getVariance () const override virtual
Returns the variance of the observations collected, or NaN if less than two observations have been collected.
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double getWeights () const inline override virtual
Since this is unweighted statistics, the sum of weights is getCount().
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double getWeightedSum () const inline override virtual
Since this is unweighted statistics, the sum of weight*value products is getSum().
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double getSqrSumWeights () const inline override virtual
Since this is unweighted statistics, the sum of squared weights is getCount().
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double getWeightedSqrSum () const inline override virtual
Since this is unweighted statistics, the sum of weight*value*value products is getSqrSum().
Implements cStatistic.
Reimplemented in cWeightedStdDev.
virtual double draw () const override virtual
Returns a number from a normal distribution with the current mean and standard deviation.
Implements cRandom.
Reimplemented in cKSplit, cHistogram, cPSquare, and cVarHistogram.
virtual void clearResult () override virtual
Clears the results collected so far.
Implements cStatistic.
Reimplemented in cWeightedStdDev, cDensityEstBase, cVarHistogram, and cHistogramBase.
virtual void saveToFile (FILE *) const override virtual
Writes the contents of the object into a text file.
Implements cStatistic.
Reimplemented in cWeightedStdDev, cKSplit, cHistogram, cPSquare, cDensityEstBase, cVarHistogram, and cHistogramBase.
virtual void loadFromFile (FILE *) override virtual
Reads the object data from a file written out by saveToFile() (or written by hand)
Implements cStatistic.
Reimplemented in cWeightedStdDev, cKSplit, cHistogram, cPSquare, cDensityEstBase, cVarHistogram, and cHistogramBase.
The documentation for this class was generated from the following file:
cstddev.h