OMNeT++ Simulation Library: cObject Class Reference
cObject Class Reference
Simulation Support
#include <cobject.h>
Description
Root of the OMNeT++ class hierarchy. cObject is a lightweight class without any data members.
cObject and its subclass cOwnedObject define an ownership mechanism. Any cObject may become owner of other objects, but owned objects must be subclassed from cOwnedObject. cObject also contains methods that allow the object to be displayed in graphical user interfaces (Tkenv, Qtenv).
It is recommended to use cObject as a base class for any class that has at least one virtual member function. This makes the class more interoperable with OMNeT++, and causes no extra overhead at all. sizeof(cObject) should yield 4 on a 32-bit architecture (4-byte vptr), and using cObject as a base class does not add anything to the size of an object, because a class with a virtual function already has a vptr. Subclasses are expected to redefine member functions such as dup(), info(), forEachChild(), etc.
Note: The (cPolymorphic, cObject) classes in OMNeT++ versions 2.x and 3.x were renamed to (cObject, cOwnedObject) in version 4.0.
Public Member Functions
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
Empty virtual functions which can be redefined in subclasses
virtual const char * getName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual std::string info () const
virtual std::string detailedInfo () const
virtual cObject * dup () const
Support for parallel execution.
These functions pack/unpack the object from/to a communication buffer, and should be redefined in classes whose instances are expected to travel across partitions.
virtual void parsimPack (cCommBuffer *buffer) const
virtual void parsimUnpack (cCommBuffer *buffer)
Miscellaneous functions.
virtual cObject * getOwner () const
virtual bool isOwnedObject () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
Helper functions.
void copyNotSupported () const
Protected Member Functions
Ownership control.
The following functions are intended to be used by derived container classes to manage ownership of their contained objects. See object description for more info on ownership management.
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cObject () inline
Constructor. It has an empty body. (The class does not have data members and there is nothing special to do at construction time.)
cObject (const cObject & other) inline
Copy constructor. It has an empty body. (The class does not have data members and there is nothing special to do at construction time.) Subclasses should call the copy constructor of their base classes from their own copy constructors.
virtual ~cObject () virtual
Destructor. It has an empty body (the class does not have data members.) It is declared here only to make the class polymorphic and make its destructor virtual.
Member Function Documentation
virtual const char* getClassName () const virtual
Returns a pointer to the class name string. This method is implemented using typeid (C++ RTTI), and it does not need to be overridden in subclasses.
Reimplemented in cWatch_cObjectPtr, cWatch_cObject, cWatch_stdstring, cWatch_uchar, cWatch_char, cWatch_bool, cGenericAssignableWatch< T >, and cGenericReadonlyWatch< T >.
Referenced by cWatch_cObject::getClassName(), and cWatch_cObjectPtr::getClassName().
virtual const char* getName () const inline virtual
Returns pointer to the object's name. It should never return nullptr. This default implementation just returns an empty string ("").
Reimplemented in cGate, cPar, cNamedObject, and cProperties.
bool isName (const char * s) const inline
Returns true if the object's name is identical to the string passed.
References omnetpp::opp_strcmp().
virtual const char* getFullName () const inline virtual
When this object is part of a vector (like a submodule can be part of a module vector, or a gate can be part of a gate vector), this method returns the object's name with the index in brackets; for example: "out[5]".
This default implementation just returns getName().
Reimplemented in cModule, cGate, cComponentType, cProperty, Sizeof, LoopVar, SiblingModuleParameterRef, and ParameterRef.
virtual std::string getFullPath () const virtual
Returns the full path of the object in the object hierarchy, like "net.host[2].tcp.winsize". This method relies on getOwner(): if there is an owner object, this method returns the owner's fullPath plus this object's fullName, separated by a dot; otherwise it simply returns fullName.
Reimplemented in cModule, and cSimulation.
const cObject* getThisPtr () const inline
Returns the this pointer. Utility function for the logging macros.
virtual std::string info () const virtual
Can be redefined to produce a one-line description of object. The string appears in the graphical user interface (Tkenv) e.g. when the object is displayed in a listbox. The returned string should possibly be at most 80-100 characters long, and must not contain newline.
See also
detailedInfo()
Reimplemented in cCanvas, cPixmapFigure, cImageFigure, cAbstractTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cAbstractShapeFigure, cPolylineFigure, cArcFigure, cLineFigure, cPoisson, cNegBinomial, cAbstractLineFigure, cGeometric, cBinomial, cGroupFigure, cBernoulli, cIntUniform, cParetoShifted, cWeibull, cTriang, cModule, cCauchy, cStudentT, cFigure, cTopology, cChiSquare, cErlang, cBeta, cWeightedStdDev, cMultiFingerprintCalculator, cGamma, cDynamicExpression, cFSM, cRealTimeScheduler, cMessage, cWatch_cObjectPtr, cSingleFingerprintCalculator, cWatch_cObject, cTruncNormal, cWatch_stdstring, cQueue, cGate, cArray, cMsgPar, cSequentialScheduler, cWatch_uchar, cNormal, cSimpleModule, cPacket, cWatch_char, cChannel, cOsgCanvas, cNEDMathFunction, cPar, cExponential, cProperty, cWatch_bool, cEvent, cDefaultList, cParImpl, cEnum, cDatarateChannel, cEventHeap, cOutVector, cGenericAssignableWatch< T >, cProperties, cNEDFunction, cConfigOption, cUniform, cPacketQueue, cStdDev, cScheduler, cGenericReadonlyWatch< T >, cExpression, cFutureEventSet, cObjectFactory, and cRegistrationList.
Referenced by cWatch_cObject::info(), and cWatch_cObjectPtr::info().
virtual std::string detailedInfo () const virtual
Can be redefined to produce a detailed, multi-line, arbitrarily long description of the object. The string appears in the graphical user interface (Tkenv) together with other object data (e.g. class name) wherever it is feasible to display a multi-line string.
Reimplemented in cMessage, cKSplit, cMsgPar, cPacket, cDensityEstBase, cPar, cEvent, cParImpl, cStdDev, cPSquare, and cXMLParImpl.
virtual cObject* dup () const virtual
Should be redefined in subclasses to create an exact copy of this object. The default implementation just throws an error, to indicate that the method was not redefined.
Reimplemented in cCanvas, cPixmapFigure, cIconFigure, cImageFigure, cAbstractImageFigure, cLabelFigure, cTextFigure, cAbstractTextFigure, cPathFigure, cPolygonFigure, cPieSliceFigure, cRingFigure, cOvalFigure, cRectangleFigure, cAbstractShapeFigure, cPolylineFigure, cArcFigure, cLineFigure, cPoisson, cNegBinomial, cAbstractLineFigure, cGeometric, cBinomial, cGroupFigure, cBernoulli, cIntUniform, cParetoShifted, cWeibull, cTriang, cCauchy, cDoubleHistogram, cStudentT, cADByStddev, cFigure, cLongHistogram, cTopology, cChiSquare, cErlang, cBeta, cTDExpandingWindows, cWeightedStdDev, cMultiFingerprintCalculator, cNoncopyableOwnedObject, cGamma, cDynamicExpression, cFSM, cMessage, cSingleFingerprintCalculator, cKSplit, cTruncNormal, cQueue, cArray, cMsgPar, cNormal, cAccuracyDetection, cPacket, cOsgCanvas, cExponential, cProperty, Sizeof, cParImpl, cEvent, cVarHistogram, LoopVar, cEnum, cEventHeap, cUniform, cPacketQueue, cProperties, cPSquare, cBoolParImpl, cDoubleParImpl, cLongParImpl, cStringParImpl, cStdDev, cXMLParImpl, cTransientDetection, SiblingModuleParameterRef, cExpression, and ParameterRef.
Referenced by cMultiFingerprintCalculator::dup().
virtual void take (cOwnedObject * obj) protected virtual
Makes this object the owner of obj. This method should be called by container classes when they take ownership of an object inserted into them.
The obj pointer should not be nullptr.
Reimplemented in cDefaultList.
virtual void drop (cOwnedObject * obj) protected virtual
Releases ownership of obj, giving it back to its default owner. This method should be called by container classes when an object is removed from the container.
The obj pointer should not be nullptr.
Reimplemented in cDefaultList.
void dropAndDelete (cOwnedObject * obj) protected
This is a shortcut for the sequence
  drop(obj);
  delete obj;
It is especially useful when writing destructors and assignment operators.
Passing nullptr is allowed.
See also
drop()
virtual void parsimPack (cCommBuffer * buffer) const virtual
Serializes the object into a buffer.
Reimplemented in cTopology, cWeightedStdDev, cNoncopyableOwnedObject, cMessage, cFSM, cHistogram, cKSplit, cQueue, cMsgPar, cArray, cOwnedObject, cPacket, cDensityEstBase, cChannel, cProperty, cEvent, cParImpl, cDefaultList, cVarHistogram, cOutVector, cProperties, cNamedObject, cPacketQueue, cStdDev, cPSquare, cStatistic, cXMLParImpl, cBoolParImpl, cDoubleParImpl, cLongParImpl, cStringParImpl, cHistogramBase, and cExpression.
virtual void parsimUnpack (cCommBuffer * buffer) virtual
Deserializes the object from a buffer.
Reimplemented in cTopology, cWeightedStdDev, cNoncopyableOwnedObject, cMessage, cFSM, cHistogram, cKSplit, cQueue, cMsgPar, cArray, cOwnedObject, cPacket, cDensityEstBase, cChannel, cProperty, cEvent, cDefaultList, cParImpl, cVarHistogram, cOutVector, cPacketQueue, cProperties, cNamedObject, cStdDev, cPSquare, cStatistic, cXMLParImpl, cBoolParImpl, cDoubleParImpl, cHistogramBase, cLongParImpl, cStringParImpl, and cExpression.
virtual cObject* getOwner () const inline virtual
Returns owner (or parent) object. This default implementation just returns nullptr.
Reimplemented in cOwnedObject, cGate, and cPar.
virtual bool isOwnedObject () const inline virtual
Returns true if this class is a subclass of cOwnedObject. This is a performance optimization, to avoid frequent calls to dynamic_cast<>. In cObject this method returns false, in cOwnedObject it returns true, and it MUST NOT be defined on any other class.
Reimplemented in cOwnedObject.
virtual void forEachChild (cVisitor * v) virtual
Enables traversing the object tree, performing some operation on each object. The operation is encapsulated in the particular subclass of cVisitor.
This method should be redefined in every subclass to call v->visit(obj) for every obj object contained.
Reimplemented in cCanvas, cModule, cFigure, cComponent, cMessage, cQueue, cMsgPar, cArray, cGate, cPacket, cSimpleModule, cChannel, cSimulation, cEvent, cDefaultList, cEventHeap, and cRegistrationList.
cObject* findObject (const char * name, bool deep = true)
Finds the object with the given name. This function is useful when called on subclasses that are containers. This method finds the object with the given name in a container object and returns a pointer to it or nullptr if the object has not been found. If deep is false, only objects directly contained will be searched, otherwise the function searches the whole subtree for the object. It uses the forEachChild() mechanism.
Do not use it for finding submodules! Use cModule::getModuleByRelativePath() instead.
void copyNotSupported () const
Convenience function: throws a cRuntimeError ("copying not supported") stating that assignment, copy constructor and dup() will not work for this object. You can call this from operator=() if you do not want to implement object copying.
The documentation for this class was generated from the following file:
cobject.h